const ORDER_COLORS = [
  ['pre-tariqa', '#7a6248'],
  ['qadiri', '#2d6a4f'],
  ['chishti', '#c07030'],
  ['naqshbandi', '#2c5f8a'],
  ['shadhili', '#3a7878'],
  ["ba'alawi", '#7a1a1a'],
  ['alawi', '#7a1a1a'],
  ['tijani', '#9a7010'],
  ['mourid', '#1a6b42'],
  ['mevlevi', '#b86820'],
  ["rifa'i", '#5a7030'],
  ['rifa', '#5a7030'],
  ['kubra', '#5a3d7a'],
  ['suhrawardi', '#7a4a8a'],
  ['khalwati', '#2d4a70'],
  ['yasawi', '#8b5a2b'],
  ['sanusi', '#4a6b8a'],
  ['inayati', '#8a3d6b'],
  ['maryami', '#3d5a8a'],
  ['universal', '#8a3d6b'],
]

export function orderColor(tariqah) {
  const t = tariqah.toLowerCase()
  for (const [key, color] of ORDER_COLORS) {
    if (t.includes(key)) return color
  }
  return '#8a6840'
}

export const CANONICAL_ORDERS = [
  {
    name: 'Pre-Tariqa Era',
    color: '#7a6248',
    keywords: ['pre-tariqa'],
    summary: `The earliest generations of Muslim mystics predate the formal organization of Sufi orders. These pioneering figures — known as the *zuhhad* (ascetics), *ubbad* (devotees), and *awliya* (friends of God) — lived in the first two centuries of Islam, when spiritual practice was transmitted through direct companionship rather than institutional affiliation. They established the foundational vocabulary of Islamic mysticism: renunciation of the world (*zuhd*), constant remembrance of God (*dhikr*), vigilant self-examination (*muhasaba*), and the interior dimensions of prayer and fasting.\n\nHasan al-Basri (d. 110 AH / 728 CE), regarded as the first link in nearly every Sufi *silsila*, combined intense piety with acute social conscience — his sermons on the fragility of worldly life set a tone Sufism would carry for centuries. Rabi\`a al-\`Adawiyya introduced the language of pure love (*mahabba*) and longing, insisting that God be worshipped not from fear or hope, but for God's own sake. Ibrahim ibn Adham, said to have been a prince who abandoned his throne, and Dhu\`l-Nun al-Misri, who gave early systematic articulation to the stations (*maqamat*) and states (*ahwal*) of the path, are among the major voices of this formative era. Al-Muhasibi developed the science of *muhasaba* — the rigorous interior accounting of the soul's motives — which would become a cornerstone of Sufi ethical psychology.\n\nThe absence of formal structure was itself a spiritual statement: these figures gathered students informally, in mosques and private homes, transmitting *adab* (spiritual courtesy) and *hal* (spiritual state) through lived proximity rather than initiation rites. Later orders would look back to them as the original wellspring, tracing every *silsila* through their names and back to the Prophet himself. They are the roots of the tree; the orders are its branches.`,
  },
  {
    name: 'Qadiriyya',
    color: '#2d6a4f',
    keywords: ['qadiri'],
    summary: `The Qadiriyya is the oldest and most geographically widespread of the major Sufi orders, founded in the lineage of \`Abd al-Qadir al-Jilani (470–561 AH / 1077–1166 CE) in Baghdad. Al-Jilani was a Hanbali jurist and preacher of extraordinary charisma whose public sermons drew vast crowds from every level of society; the devotional movement that crystallized around him after his death became, within two centuries, the most expansive Sufi order in the Islamic world. The Qadiri *silsila* passes through \`Ali ibn Abi Talib and Hasan al-Basri, rooting the order's legitimacy in the earliest generation of Islamic piety.\n\nThe order's core practices include recitation of the *Qadiri wird* (a specific set of prayers attributed to al-Jilani), intensive *dhikr* sessions, and deep veneration of the founding master. Al-Jilani's major work, *Futuh al-Ghayb* (Revelations of the Unseen), remains one of the most widely read Sufi texts in the world. The order spread first through Iraq and Persia, then through the Indian subcontinent — where it became a significant force from the 13th century onward — and subsequently through sub-Saharan Africa, Southeast Asia, and Central Asia. Its branches include the Qadiriyya-Boutchichiyya of Morocco, the Ghawthiyya of the Punjab, and many regional variants across the Muslim world.\n\nThe order is characterized by relative openness in its practice — there is no single rigid form imposed uniformly across all branches — which may account for much of its remarkable geographic reach. Al-Jilani's *maqam* (spiritual station) is described by later masters as *qutbaniyya* — the pole around which the spiritual world turns — a claim that became the basis for the extraordinary reverence his name commands across almost every Sufi tradition. The dargah of \`Abd al-Qadir al-Jilani in Baghdad remains one of the most visited shrines in the Islamic world.`,
  },
  {
    name: 'Chishtiyya',
    color: '#c07030',
    keywords: ['chishti'],
    summary: `The Chishtiyya is the dominant Sufi order of the Indian subcontinent, tracing its chain to Khwaja Mu\`in al-Din Chishti (536–633 AH / 1141–1236 CE), who carried the order from Khurasan to the city of Ajmer in Rajasthan. The order takes its name from the town of Chisht near Herat, Afghanistan, where the early masters of the lineage were based. Mu\`in al-Din's arrival in India coincided with the beginning of the Ghurid conquest, but the Chishtis deliberately maintained distance from political power — a principle that became one of the order's most defining characteristics. The Chishti masters refused gifts from rulers, lived in voluntary poverty, and kept their *khanqahs* open to all visitors regardless of religion, caste, or social class.\n\nThis radical openness, combined with the use of *sama\`* — devotional music and poetry as a means of intensifying spiritual longing — gave the Chishtiyya a unique cultural footprint in India. The order's greatest figures built a network of *khanqahs* that shaped the spiritual life of medieval South Asia: Qutb al-Din Bakhtiyar Kaki in Delhi, Farid al-Din Ganj-i-Shakar in Pakpattan, Nizam al-Din Awliya in Delhi, and Burhan al-Din Gharib in Khuldabad. The dargahs of these masters became centers of popular devotion attracting Muslims and Hindus alike, and many continue as living pilgrimage sites today.\n\nThe Chishtiyya's major sub-branches — Nizamiyya, Sabiriyya, and their many descendants — remained active through the Mughal period and into the modern era. The *qawwali* tradition that the Chishtis nurtured is now recognized globally as one of the world's great sacred music forms. The order's combination of strict interior discipline with outward warmth and social accessibility represents one of the most successful models of spiritual transmission in Islamic history.`,
  },
  {
    name: 'Naqshbandiyya',
    color: '#2c5f8a',
    keywords: ['naqshbandi'],
    summary: `The Naqshbandiyya is one of the largest and most politically consequential of the Sufi orders, tracing its spiritual lineage to Abu Bakr al-Siddiq (the first Caliph) through a chain that includes Bayazid al-Bistami and culminates in Baha\` al-Din Naqshband (718–791 AH / 1318–1389 CE) of Bukhara. The order is distinguished by several principles that set it apart from all others: *dhikr khafi* (silent, interior remembrance) rather than the audible *dhikr* of most orders; *rabita* (conscious spiritual connection between disciple and master); and the principle of *khalwat dar anjuman* — solitude in the crowd, maintaining inner recollection amid full worldly engagement. Unlike orders that emphasize retreat from the world, the Naqshbandiyya insists on presence within it.\n\nThe order spread rapidly through Central Asia, Ottoman Anatolia, and the Indian subcontinent. Its most consequential reformer was Ahmad Sirhindi (971–1034 AH / 1564–1624 CE), who reorganized the order as the Mujaddidi branch and exerted decisive influence on Mughal court politics and the articulation of Sunni orthodoxy in South Asia. The Khalidi branch, founded in the early 19th century by Khalid al-Baghdadi, spread through the Ottoman Empire and remains one of the most active Naqshbandi branches in Turkey, Kurdistan, and the Arab world. The Haqqani branch became prominent among Western converts in the late 20th century.\n\nThe Naqshbandiyya's consistent engagement with political authority — advising rulers, resisting colonial occupation, shaping religious law — makes it the most politically active of the major Sufi orders. Figures in this lineage led resistance movements against Russian expansion in the Caucasus, British rule in India, and French colonialism in North Africa. This combination of interior silence and exterior engagement gives the order its characteristic flavor: the Naqshbandi master is as likely to be found at court as in retreat.`,
  },
  {
    name: 'Shadhiliyya / Alawiyya',
    color: '#3a7878',
    keywords: ['shadhili'],
    summary: `The Shadhiliyya was founded by Abu al-Hasan al-Shadhili (593–656 AH / 1196–1258 CE), a Moroccan-born shaykh who settled in Egypt and whose lineage became one of the most intellectually fertile and geographically widespread in the Sufi world. Unlike the Qadiriyya or Chishtiyya, the Shadhiliyya does not require withdrawal from the world or the adoption of distinctive dress; al-Shadhili insisted on full participation in normal professional and social life, with interior practice sustained through the *hizb* (litany) and constant inner awareness. This accessibility made the order attractive to scholars, lawyers, merchants, and, in later centuries, Western converts to Islam.\n\nThe great works of al-Shadhili's student Ibn \`Ata\` Allah al-Iskandari — especially the *Hikam* (Aphorisms) — became foundational texts of the broader Sufi tradition, studied far beyond the boundaries of the order. The Shadhili tree branched prolifically over subsequent centuries: the Jazuliyya and Wazzaniyya of Morocco, the Darqawiyya, the Alawiyya of Algeria (founded by Ahmad ibn Mustafa al-Alawi in the 20th century), the Yashrutiyya, and dozens of other orders all trace their lineage through al-Shadhili. In the Levant and Egypt, the order produced a series of major scholar-saints who combined rigorous legal scholarship with deep mystical practice.\n\nThe Shadhiliyya is particularly strong in North Africa, Egypt, the Levant, and among Western converts to Islam. Its tradition of uniting interior practice with outward normality — combined with the extraordinary literary richness of its *ahzab* (litanies) and the intellectual sophistication of its major texts — makes it one of the most enduring and adaptable of the great Sufi families.`,
  },
  {
    name: "Ba'alawiyya",
    color: '#7a1a1a',
    keywords: ["ba'alawi", 'alawi'],
    summary: `The Ba\`alawiyya (also called the Tariqa \`Alawiyya or the Hadhrami Tariqa) is a Sufi order originating in the Hadhramaut valley of Yemen, founded in the lineage of Muhammad ibn \`Ali Ba\`Alawi (d. 653 AH / 1255 CE), known as al-Faqih al-Muqaddam. The order's members belong to the *Sadah* — sayyids who combine genealogical descent from the Prophet through the Husayni line with spiritual transmission. This fusion of bloodline and *silsila* gives the Ba\`alawi tradition its distinctive character: a path in which the love of the Prophet is not merely a spiritual practice but a living inheritance.\n\nThe Ba\`alawi masters describe their way as *al-tariq al-wusta* — the Middle Way: strict adherence to Islamic law, intellectual theological formation, and interior purification, without the elaborate ritual structures of other orders. Their *khanqahs* and *ribats* were organized above all around *adab* (spiritual courtesy), *mahabba* (love), and the formation of character through proximity to a living master. The order spread along the maritime trade routes of the Indian Ocean — from Yemen to the Swahili Coast of East Africa, coastal India, and the Malay Archipelago — carried by Hadhrami merchant-scholars who established diaspora communities across the Muslim world.\n\nImam al-Haddad (1044–1132 AH / 1634–1720 CE), the order's greatest systematizer, wrote works — including the *Ratib al-Haddad* and *Risalat al-Mu\`awana* — that became standard texts of piety across the Indian Ocean world. Today the Ba\`alawiyya is extremely active in Indonesia, Malaysia, Singapore, East Africa, and the Gulf, representing one of the most living expressions of Prophetic-Hadhrami spirituality in the contemporary Muslim world.`,
  },
  {
    name: 'Suhrawardiyya / Kubrawiyya',
    color: '#7a4a8a',
    keywords: ['suhrawardi', 'kubra'],
    summary: `The Suhrawardiyya was founded by Shihab al-Din \`Umar al-Suhrawardi (539–632 AH / 1144–1234 CE), whose *khanqah* in Baghdad became the model for organized Sufi institutional life throughout the Islamic world. His *\`Awarif al-Ma\`arif* (The Gifts of Gnosis) is one of the most comprehensive early manuals of Sufi theory and practice — a systematic treatment of *adab*, *dhikr*, *suhba*, and the stations of the path — and it was used as a textbook across the Islamic world for centuries. The Suhrawardiyya spread primarily through Persia and the Indian subcontinent, where it became a major presence alongside the Chishtiyya.\n\nThe Kubrawiyya was founded by Najm al-Din Kubra (540–618 AH / 1145–1221 CE) in Khurasan. Kubra developed a sophisticated visionary psychology centered on the inner lights — the subtle colors that appear in advanced states of *dhikr* — which he mapped with remarkable precision in works like *Fawa\`ih al-Jamal* and *\`Ayn al-Hayat*. His school was particularly influential on the Persian poetic and mystical tradition, and several of its branches — including the Hamadaniyya, the Nurbakhshiyya, and the Dhahabi — became important regional orders in their own right.\n\nBoth families are grouped here because of their shared Central Asian and Persian origin and their overlapping intellectual and institutional history. Together they represent the great tradition of Khurasani and Iraqi Sufi thought that formed the backbone of medieval Persian mystical culture — the tradition from which figures like Rumi, Jami, and the Persian *masnavi* poets all drank.`,
  },
  {
    name: 'Khalwatiyya',
    color: '#2d4a70',
    keywords: ['khalwati'],
    summary: `The Khalwatiyya was founded by \`Umar al-Khalwati (d. 800 AH / 1397 CE) in Anatolia, taking its name from the practice of *khalwa* — extended periods of solitary spiritual retreat, typically forty days — modeled on the Quranic account of Moses' vigil on Sinai and the Prophet's retreat in the Cave of Hira\`. The forty-day retreat (*chilla*) is the central spiritual technology of the order, an intensive period of fasting, reduced sleep, and concentrated *dhikr* in isolation, designed to strip away the ego's habitual defenses and open the heart to direct divine presence.\n\nThe Khalwatiyya became one of the most important Sufi orders of the Ottoman Empire, enjoying strong court patronage and producing major figures in spiritual, scholarly, and musical life. Its major branches include the Jarrahiyya (founded by Pir Nureddin Jerrahi in Istanbul in the early 18th century, now active internationally), the Sunbuliyya, the Ramazaniyya, and the Misirliyya. In Egypt, the order became deeply rooted in the al-Azhar scholarly establishment through a chain that runs from Mustafa al-Bakri through Muhammad al-Hafni, Ahmad al-Dardir, and Ahmad al-Sawi — figures who combined authoritative Maliki legal scholarship with the interior disciplines of the Khalwati path.\n\nThe order's emphasis on *khalwa* gives it a distinctively interior, contemplative character. Where other orders organize communal life around the public *hadhra* or *sama\`*, the Khalwatiyya's most characteristic moment is solitary — the individual alone before God in a darkened cell, stripped of distractions, reduced to the bare act of remembrance. This rigor attracted scholars and intellectuals who sought a demanding interior practice compatible with their professional lives.`,
  },
  {
    name: "Rifa'iyya",
    color: '#5a7030',
    keywords: ["rifa'i", 'rifa'],
    summary: `The Rifa\`iyya, founded by Ahmad ibn \`Ali al-Rifa\`i (512–578 AH / 1118–1182 CE) in the marshlands of southern Iraq, is one of the oldest of the Sufi orders and one of the most distinctive in its ritual expression. Al-Rifa\`i was renowned for his extreme humility, his tender love for the poor and the sick, and his insistence that the highest spiritual attainment was not ecstasy but complete self-erasure — the fana\` of the *ana* (the "I") in the reality of God. He is reported to have said: "My way is the way of poverty, hunger, wakefulness, and silence."\n\nThe order became widely known for its *hadhra* — intense communal *dhikr* sessions that, in certain branches, culminated in dramatic feats attributed to the spiritual energy of the gathering: handling fire, piercing the body with iron implements without injury. These practices — celebrated by followers as manifestations of the masters' *baraka* and criticized by reformers as unlawful innovation — gave the Rifa\`iyya a visible cultural presence that made it both popular and controversial. At the heart of the tradition, however, is al-Rifa\`i's own example: a man of extraordinary gentleness who cared personally for lepers and outcasts and who wept constantly in prayer.\n\nThe order spread through the Arab world, Anatolia, and the Balkans, and it remains particularly active in Syria, Egypt, and Iraq. Al-Rifa\`i's tomb in Umm \`Ubayda in southern Iraq is a major pilgrimage site. The *silsila* passes through Ahmad al-Rifa\`i's great-uncle Mansur al-Bata\`ihi and back through the standard chain to the Prophet.`,
  },
  {
    name: 'Mevleviyya',
    color: '#b86820',
    keywords: ['mevlevi'],
    summary: `The Mevleviyya (Arabic: Mawlawiyya) arose in the lineage of Jalal al-Din Rumi (604–672 AH / 1207–1273 CE), the Persian poet-mystic whose *Masnavi-yi Ma\`nawi* — six volumes of spiritual verse totaling some 25,000 couplets — stands among the greatest works of world literature. Rumi spent most of his adult life in Konya in Anatolia, where his *khanqah* became a center of extraordinary spiritual and artistic vitality. The order was formally organized by his son Sultan Walad, who systematized the *sama\`* ceremony — the distinctive whirling meditation of the "turning dervishes" — into a formal liturgical practice complete with music, prescribed costume, and symbolic movement.\n\nThe *sama\`* is understood as a meditation on cosmic order: the turning of the dervish mirrors the rotation of the planets around the sun, and the soul's circumambulation of the divine center. The ceremony unfolds in five *selam* (salutations), each representing a stage of spiritual ascent, accompanied by the *ney* (reed flute) — the instrument that opens the *Masnavi* as the emblem of the soul's longing for its origin. The Mevlevi tradition became deeply embedded in Ottoman court culture, producing masters of music, calligraphy, poetry, and architecture alongside its spiritual practice.\n\nAfter Ataturk's abolition of the dervish orders in 1925, the Mevleviyya was suppressed in Turkey but survived through diaspora communities and the transmission of the *sema\`* as a performing art. It was partially rehabilitated and the annual ceremony in Konya is now a major cultural event. Active *tekkes* (lodges) continue in Turkey, Syria, and internationally, and Rumi's poetry — especially in Barks' English adaptations — has made the Mevlevi tradition one of the most recognized expressions of Sufism in the Western world.`,
  },
  {
    name: 'Yasawiyya',
    color: '#8b5a2b',
    keywords: ['yasawi'],
    summary: `The Yasawiyya is the oldest Sufi order of Central Asia, founded by Ahmad Yasawi (c. 487–562 AH / 1093–1166 CE) in the region of present-day southern Kazakhstan. Yasawi is a pivotal figure in Islamic history because he chose to write his principal work — the *Diwan-i Hikmat* (Book of Wisdom) — in Turkic rather than Arabic or Persian. This decision made the *Hikam* the foundational text of Turkic Sufi literature and a primary vehicle for the Islamization of the Turkic-speaking nomadic and semi-nomadic peoples of the steppe: the Kazakhs, Uzbeks, Kyrgyz, Uyghurs, and their neighbors.\n\nThe *Hikam* verses are short, direct, rhythmic, and deeply personal — Yasawi speaks in the first person of his own sins, his longing, his shame before God, and his desire for annihilation in the divine. This confessional directness, far from the elaborate Persian metaphysics of the Khurasani tradition, made the text accessible and memorable to populations with little formal Islamic education. At sixty-three — the age at which the Prophet died — Yasawi is said to have descended into an underground cell (*chilla-khana*) beneath his *tekke* in Yasi (modern Turkestan, Kazakhstan) and spent the remainder of his life there in perpetual retreat, refusing to outlive the Prophet even in years.\n\nHis tomb in Turkestan, rebuilt on a monumental scale by Timur in the 14th century as an act of imperial piety, became one of the major pilgrimage sites of the eastern Islamic world. The Yasawiyya's lodges spread across the steppe and into the Volga region, playing a crucial role in the transmission of a distinctively Central Asian Sufi practice that honored both Islamic law and the cultural sensibilities of nomadic peoples.`,
  },
  {
    name: 'Tijaniyya',
    color: '#9a7010',
    keywords: ['tijani'],
    summary: `The Tijaniyya was founded by Ahmad al-Tijani (1150–1230 AH / 1737–1815 CE), an Algerian-born scholar who claimed to have received his *wird* — the order's distinctive litany — directly from the Prophet Muhammad in a waking vision (*yaqza*) in 1781. This claim set the Tijaniyya apart from every other Sufi order: al-Tijani taught that membership in the Tijaniyya superseded all other spiritual affiliations, that the *Salat al-Fatihi* (the prayer revealed to him) was worth more than sixty thousand ordinary prayers, and that sincere Tijanis were guaranteed paradise through the Prophet's direct intercession. These bold claims provoked intense controversy with the established orders while generating extraordinary devotion among followers.\n\nThe Tijaniyya's spread through West Africa in the 19th century was among the most dramatic religious expansions of the modern era. Carried by scholars like al-Hajj \`Umar Tall (who launched a *jihad* state across the Sahel in its name) and Muhammad al-Ghali al-Tijani, the order swept through Senegal, Mauritania, Guinea, Mali, Nigeria, and Sudan, becoming the largest Sufi order in sub-Saharan Africa. Today it claims tens of millions of followers across the African continent and its diaspora.\n\nThe Fayda Tijaniyya, centered on Ibrahim Niasse (1900–1975 CE) of Medina Kaolack in Senegal, represents the order's most dynamic 20th-century expression. Niasse claimed a special *fayda* (flood of divine grace) that democratized the highest spiritual states, making mass spiritual realization available through collective *dhikr* — a departure from the individual-transmission model of classical Sufism. The Fayda attracted millions of followers across West Africa and the diaspora and continues to expand today.`,
  },
  {
    name: 'Mouridiyya',
    color: '#1a6b42',
    keywords: ['mourid'],
    summary: `The Mouridiyya (Murīdiyya) was founded by Amadou Bamba Mbacké (1270–1346 AH / 1853–1927 CE) in Senegal, making it one of the very few major Sufi orders to have originated in sub-Saharan Africa. The order emerged within the Qadiri tradition but developed its own distinctive theological emphasis: above all, the spiritual efficacy of *khidma* — service, labor, and devotion to the shaykh as a path to God. Amadou Bamba taught that in an age when the conditions for classical spiritual practice had been disrupted by colonial conquest, disciplined work performed with a pure heart and offered to God through the intermediary of the shaykh was itself a form of *ibada* (worship).\n\nAmadou Bamba's life was shaped by his confrontation with the French colonial administration, which viewed his rapidly growing movement with alarm. His exiles to Gabon (1895–1902) and Mauritania (1903–1907) became, in popular Mourid memory, acts of spiritual triumph — the saint enduring suffering as the Companions had endured theirs — and his eventual return to Senegal transformed him into a symbol of dignified resistance. He was also a prolific Arabic poet whose *qasa\`id* (odes) on the Prophet and on the spiritual path now form the sacred literature of the order, chanted at *dairas* (local associations) around the world.\n\nToday the Mouridiyya, centered on the holy city of Touba — where Amadou Bamba is buried in the Grand Mosque he himself designed — is the most politically influential religious institution in Senegal, with strong ties to agriculture (the peanut basin), commerce, and urban organization. A worldwide network of *dairas* connects Mourid communities from Dakar to New York, Paris, and Tokyo, making it one of the most globally active of the contemporary Sufi orders.`,
  },
  {
    name: 'Sanusiyya',
    color: '#4a6b8a',
    keywords: ['sanusi'],
    summary: `The Sanusiyya was founded by Muhammad ibn \`Ali al-Sanusi (1202–1276 AH / 1787–1859 CE), an Algerian scholar who established his order in Libya and built one of the most remarkable religious-social networks of the 19th century. Al-Sanusi combined rigorous Maliki-Shafi\`i scholarship with Sufi spirituality drawn from the Shadhili-Idrisiyya lineage of Ahmad ibn Idris, adding a strong commitment to *ijtihad* (independent legal reasoning) and a suspicion of blind *taqlid* (imitation). This made the Sanusiyya simultaneously a Sufi order, a reform movement, and an educational institution.\n\nThe *zawiya* network that al-Sanusi established across the Libyan Desert and the Sahara was a remarkable feat of institution-building. Each *zawiya* served as a mosque, Quranic school, hostel for travelers, court of arbitration for tribal disputes, and trading post — a complete miniature civilization planted in the desert. The network grew rapidly across Libya, the Sahara, Sudan, and Egypt, becoming the dominant religious institution of a vast territory with few other centers of learning or governance.\n\nThe Sanusiyya became closely identified with Libyan national identity: the founder's grandson, Muhammad Idris al-Sanusi, became the first king of independent Libya in 1951, after the order played a central role in organizing resistance to Italian colonial occupation (1911–1943) — one of the bloodiest colonial wars in African history. This combination of spiritual authority, educational infrastructure, and political leadership makes the Sanusiyya one of the most historically consequential of the Sufi orders in the modern era.`,
  },
  {
    name: 'Universal Sufi / Inayati',
    color: '#8a3d6b',
    keywords: ['inayati', 'maryami', 'universal'],
    summary: `The Universal Sufi movement was founded by Inayat Khan (1299–1346 AH / 1882–1927 CE), an Indian musician of Chishti lineage who traveled to Europe and America in 1910 and established a form of Sufism that transcended confessional boundaries. Inayat Khan presented the mystical core of Sufism — the purification of the heart, the discovery of the divine presence in all of creation, the harmonization of the self through beauty and service — as a universal spiritual path available to people of all religious backgrounds. He drew on Sufi metaphysics, Indian classical music (he was a master of the *vina*), and the idea that all the world's wisdom traditions point toward the same divine reality.\n\nHis teaching, which he called the "Message of the Heart," was influential among early 20th-century European and American spiritual seekers. His daughter Noor Inayat Khan became a British SOE agent in occupied France during World War II — one of the war's most celebrated figures of courage — and was executed at Dachau in 1944. The Inayati Order continues today as an international organization based in his transmission.\n\nThe Maryamiyya, founded by Frithjof Schuon (1325–1419 AH / 1907–1998 CE) within the Shadhili-Alawi lineage, represents a related but distinct current: intellectually oriented, rooted in the Traditionalist or Perennialist philosophy associated with René Guénon and Ananda Coomaraswamy, and emphasizing the esoteric unity underlying the great revealed religions. Schuon's order attracted Western intellectuals and converts and was influential in academic religious studies. Both movements are gathered here as expressions of Sufism's encounter with modernity and the Western world — attempts to articulate, each in its own way, what the interior tradition of Islam offers to those formed by other cultures.`,
  },
]

export function orderFamily(tariqah) {
  const t = tariqah.toLowerCase()
  for (const order of CANONICAL_ORDERS) {
    if (order.keywords.some(kw => t.includes(kw))) {
      return { name: order.name, color: order.color }
    }
  }
  return { name: 'Independent / Other', color: '#8a6840' }
}

export const LEGEND_ENTRIES = [
  { label: 'Pre-tariqa era', color: '#7a6248' },
  { label: 'Qadiriyya', color: '#2d6a4f' },
  { label: 'Chishtiyya', color: '#c07030' },
  { label: 'Naqshbandiyya', color: '#2c5f8a' },
  { label: 'Shadhiliyya / Alawiyya', color: '#3a7878' },
  { label: "Ba'alawiyya", color: '#7a1a1a' },
  { label: 'Tijaniyya', color: '#9a7010' },
  { label: 'Mouridiyya', color: '#1a6b42' },
  { label: "Mevleviyya / Rifa'iyya", color: '#b86820' },
  { label: 'Suhrawardiyya / Kubrawiyya', color: '#7a4a8a' },
  { label: 'Khalwatiyya', color: '#2d4a70' },
  { label: 'Others', color: '#8a6840' },
]
